// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0njaHUcjo3dH5tCo1zlCakFIXCeS1iKQ',
    appId: '1:231363360663:web:4c430e6d5ab395369a36d2',
    messagingSenderId: '231363360663',
    projectId: 'e-commerce-50035',
    authDomain: 'e-commerce-50035.firebaseapp.com',
    storageBucket: 'e-commerce-50035.firebasestorage.app',
    measurementId: 'G-0Q8GNLHYWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk02IgxIXJfcrynpHael954Rg-dcaccxw',
    appId: '1:231363360663:android:5569c247651f2adf9a36d2',
    messagingSenderId: '231363360663',
    projectId: 'e-commerce-50035',
    storageBucket: 'e-commerce-50035.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWAOJp5JKWtXSuAnru0xd8elPxe_4kZK8',
    appId: '1:231363360663:ios:855589b6e3fdaf6f9a36d2',
    messagingSenderId: '231363360663',
    projectId: 'e-commerce-50035',
    storageBucket: 'e-commerce-50035.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
